// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package partial

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func TodoForm(e error) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"add-todo\" action=\"/todos\" hx-post=\"/todos\" class=\"flex flex-row space-x-3 justify-between items-center p-4\" hx-swap=\"outerHTML\"><input type=\"text\" name=\"title\" id=\"new-todo-title\" class=\"input input-bordered w-full max-w-sm\" required minlength=\"3\" autofocus autocomplete=\"off\" placeholder=\"Enter new to-do...\"><div class=\"tooltip\" data-tip=\"Add new to-do\"><button type=\"submit\" class=\"btn btn-secondary\"><i data-feather=\"plus\" class=\"w-4 h-4\"></i></button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if e != nil {
			templ_7745c5c3_Err = ServerError(e).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
